version: '3.1'

services:

  wordpress:
    image: erwin82/wordpress:latest
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_PASSWORD: example
      APACHE_HTTP_PORT_NUMBER: 8080
      APACHE_HTTPS_PORT_NUMBER: 8443
      APACHE_SERVER_NAME: muellerpublic.de
      APACHE_SERVER_ADMIN_EMAIL: admin@muellerpublic.de

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
